#!/usr/bin/env zsh

# https://superuser.com/a/556006
# $name is the assigned variable
# everything after '?' is what
# you see as the prompt
xzarchive () {
  FILES=${@}

  read "name?Name of archive: "

  XZ_OPT=-e9 tar -cJvf $PWD/$name.tar.xz $FILES
}
